data <- read.csv(pipe('egrep \'^Date|^[1-2]/2/2007\' household_power_consumption.txt'), header=T, sep=';')
png(file="plot4.png", width=480, height=480, units = "px")
par(mfrow = c(2,2))
data$DateTime <- strptime(paste(data$Date, data$Time, sep=" "), format="%d/%m/%Y %H:%M:%S")
plot(data$DateTime, data$Global_active_power, type="l", ylab="Global Active Power", xlab="")
plot(data$DateTime, data$Voltage, type="l", ylab="Voltage", xlab="datetime")
plot(data$DateTime, data$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(data$DateTime, data$Sub_metering_2, type="l", col="red")
lines(data$DateTime, data$Sub_metering_3, type="l", col="blue")
legend("topright",col = c("black","red","blue"), bty = "n", lty = 1,legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$DateTime, data$Global_reactive_power, type="l", ylab="Global_reactive_power", xlab="datetime")
dev.off()